#!/usr/bin/env bash
# Prepares a container WITHOUT systemd (e.g. a cloud dev sandbox) to run tests/e2e/e2e.sh.
# Real servers and GitHub Actions runners do not need this.
#
#   - installs a minimal `systemctl` stand-in that the Coolify installer can drive
#     (status/start/restart for ssh and docker)
#   - optionally routes Docker Hub pulls through a registry mirror (E2E_REGISTRY_MIRROR),
#     for shared-IP networks that hit Docker Hub's anonymous rate limit
#   - pre-seeds /etc/docker/daemon.json with Coolify's default address pool so the
#     installer leaves the file (and the mirror setting) alone
#   - starts dockerd and sshd
#
# Usage: sudo E2E_REGISTRY_MIRROR=https://mirror.gcr.io tests/e2e/sandbox-prep.sh
set -euo pipefail

[ "$(id -u)" -eq 0 ] || {
    echo "run as root" >&2
    exit 1
}

SHIM_DIR=/usr/local/sbin
LOG_DIR=/var/log/e2e-sandbox
mkdir -p "$LOG_DIR"

start_dockerd() {
    pkill -x dockerd 2>/dev/null || true
    for _ in $(seq 1 30); do pgrep -x dockerd >/dev/null || break; sleep 0.5; done
    rm -f /var/run/docker.pid
    nohup dockerd >>"$LOG_DIR/dockerd.log" 2>&1 &
    for _ in $(seq 1 60); do
        docker info >/dev/null 2>&1 && return 0
        sleep 0.5
    done
    echo "dockerd did not start; see $LOG_DIR/dockerd.log" >&2
    return 1
}

start_sshd() {
    mkdir -p /run/sshd
    ssh-keygen -A >/dev/null
    pgrep -x sshd >/dev/null || /usr/sbin/sshd
}

if [ "${1:-}" = "--start-dockerd" ]; then
    start_dockerd
    exit
fi
if [ "${1:-}" = "--start-sshd" ]; then
    start_sshd
    exit
fi

command -v sshd >/dev/null || DEBIAN_FRONTEND=noninteractive apt-get install -y -qq openssh-server >/dev/null
command -v dockerd >/dev/null || {
    echo "dockerd is not installed" >&2
    exit 1
}

self="$(readlink -f "$0")"
cat >"$SHIM_DIR/systemctl" <<EOF
#!/usr/bin/env bash
# e2e sandbox stand-in for systemctl (generated by tests/e2e/sandbox-prep.sh)
args=()
for a in "\$@"; do case "\$a" in --*) ;; *) args+=("\$a") ;; esac; done
verb="\${args[0]:-}"; unit="\${args[1]:-}"; unit="\${unit%.service}"
case "\$verb:\$unit" in
  status:ssh|status:sshd|is-active:ssh|is-active:sshd) pgrep -x sshd >/dev/null ;;
  start:ssh|start:sshd|restart:ssh|restart:sshd) "$self" --start-sshd ;;
  status:docker|is-active:docker) docker info >/dev/null 2>&1 ;;
  start:docker|restart:docker) "$self" --start-dockerd ;;
  *) exit 0 ;;
esac
EOF
chmod 755 "$SHIM_DIR/systemctl"

mkdir -p /etc/docker
if [ -n "${E2E_REGISTRY_MIRROR:-}" ]; then
    mirrors="\"registry-mirrors\": [\"$E2E_REGISTRY_MIRROR\"],"
else
    mirrors=""
fi
cat >/etc/docker/daemon.json <<EOF
{
  $mirrors
  "log-driver": "json-file",
  "log-opts": { "max-size": "10m", "max-file": "3" },
  "default-address-pools": [ {"base":"10.0.0.0/8","size":24} ]
}
EOF

start_dockerd
start_sshd
echo "sandbox ready: $(docker version --format 'docker {{.Server.Version}}'), sshd pid $(pgrep -x sshd | head -n1)"
