services:
  web:
    build: .
    ports:
      - "3000:3000"
    restart: sometimes
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: not-a-duration
   environment:
      - MODE=production
